### ISSUE TITLE
Get some simple stats on Fingertips

### ISSUE THREAD

**Issue by julianflowers** [ropensci/fingertipsR#37]
Could we add a simple function to extract basic stats on number of profiles/ indicators etc. Janine Dellar wanted these stats and they maybe useful for anyone who wants to know how much there is in Fingertips

`

### counts profiles, total published indicators, and distinct indicators in fingertips 
fingertips_stats <- function(){
    
  
  cat("This may take a few moments... ")
  
  require(glue, quietly = TRUE)
  require(fingertipsR, quietly = TRUE)
    
  profiles_n <- length(unique(profiles()$ProfileName))
  indicatorid_n <- length(unique(indicators()$IndicatorID))
  indicators_n <- length(indicators()$IndicatorID)
  
  result <- glue(
    
    "On ",  {format(Sys.Date(), "%d/%m/%Y")}, " Fingertips consisted of ",  {profiles_n},  " profiles, ",
    {indicators_n},  " indicators and ", {indicatorid_n}, " distinct indicators."
    
  )
  
result
}
`

gives 
This may take a few moments... On 02/01/2018 Fingertips consisted of 73 profiles, 4559 indicators and 1647 distinct indicators.

**Comment by julianflowers** [comment]
Could I do this via a pull request?

**Comment by sebastian-fox** [comment]
Yes, can do. I'd prefer to use `paste` instead of `glue` as this reduces dependencies on other packages (see comment on [predict_indicator()](https://github.com/PublicHealthEngland/fingertipsR/issues/2#issuecomment-355919291) re: [rOpenSci](https://github.com/ropensci/onboarding/issues/168#issuecomment-352485943).

Otherwise, I can do this for you later today or tomorrow. Let me know if you'd like to do a pull request as practise?

**Comment by julianflowers** [comment]
Agreed
Never done a pull request so yes be good practice - can you guide me through it

**Comment by sebastian-fox** [comment]
done (as I want to submit to CRAN) - 6a43c7fc9dc0f68c8ff09a79f96f55b2347f23a1

**Comment by julianflowers** [comment]
Thanks
Sorry I didn’t finalise
