### ISSUE TITLE
Cannot download indicator 698 fingertips data

### ISSUE THREAD

**Issue by samrickman** [ropensci/fingertipsR#72]
Hi,

I have used the fingertipsR package before and it's great. Thanks!

However, I now cannot get it to work in the most basic way. I am pretty sure the syntax I am using has worked before:

**1. Find desired indicator number**

`
inds <- indicators_unique(ProfileID = 20) # get list of GP indicators 

inds[grep("Nursing", inds$IndicatorName),] # Find nursing home indicator
`

This works as expected:

`# A tibble: 1 x 2
IndicatorID IndicatorName        
<int> <fct>                
1         698 Nursing home patients`

**2. Fetch indicator data**

`    nursing_homes <- fingertips_data(IndicatorID = 698)
;    dim(nursing_homes)
`

It does not produce an error but there are 0 rows:

`[1]  0 26`

**3. Try other options**

If I try to use the fingertips_data() function with IndicatorID 247, it works perfectly. 

However, in both of the following cases it returns 0 rows:

`gp_profile <- fingertips_data(ProfileID = 20)
`

`domains <-profiles() %>% filter(ProfileID == 20) %>% pull(DomainID)  ; gp_data <- fingertips_data(DomainID = domains) `  

it returns 0 rows.

I am running R on an x86_64-pc-linux-gnu, version 3.5.3 (Great Truth). I installed the fingertipsR package on this machine for the first time today, 22nd May 2019.

What am I missing?

**Comment by sebastian-fox** [comment]
Hi @samrickman - this is one of the most common questions I get. I should probably add a warning message to help users.

Your issue is that `fingertips_data()` defaults to `AreaTypeID = 102` (County & UA). You want GP data, which is `AreaTypeID = 7` (see `area_types()` for the ids). So this should give you some data:

```
library(fingertipsR)
nursing_homes <- fingertips_data(IndicatorID = 698, AreaTypeID = 7) 

```

To see which indicators are available at each `AreaTypeID` you can use the `indicator_areatypes()` function.

If this works, please could you close the issue? 
Thanks

**Comment by samrickman** [comment]
Thanks a lot that did the trick.
