### ISSUE TITLE
nearest_neighbour

### ISSUE THREAD

**Issue by LukeGray-sos** [ropensci/fingertipsR#82]
Hello,

the nearest_neighbours function on version 0.2.9, is still showing as the pre Apr 19 neighbours, is this likely to be updated or provide an option for the post change CIPFA groups?

Thanks
Luke

**Comment by sebastian-fox** [comment]
Hi @LukeGray-sos - thanks for getting in touch and putting this on my radar. Yes, we'll update this for the next release of the package. With holidays and other pressing data updates for Fingertips it's likely to be a couple of months before it is available

**Comment by sebastian-fox** [comment]
Hi @LukeGray-sos - having told you it won't be possible, it turns out that the data was available, we'd just got preoccupied with other tasks and hadn't remembered that we'd made it available. I've made it available through the package now. You can access it via the dev version:
```
remotes::install_github("rOpenSci/fingertipsR",
                        build_vignettes = TRUE,
                        dependencies = "suggests")
```
If this is doing what you're expecting could you close the issue please?
Many thanks
