### ISSUE TITLE
Docs build failure

### ISSUE THREAD

**Issue by jeroen** [ropensci/fingertipsR#92]
See: https://dev.ropensci.org/blue/organizations/jenkins/fingertipsR/detail/fingertipsR/37/pipeline

```
-- Building articles -----------------------------------------------------------
Writing 'articles/index.html'
Reading 'vignettes/lifeExpectancy.Rmd'
-- RMarkdown error -------------------------------------------------------------
Quitting from lines 94-97 (lifeExpectancy.Rmd) 
Error : Can't subset columns that don't exist.
✖ Column `Indicator Name` doesn't exist.
```

**Comment by sebastian-fox** [comment]
Thanks @jeroen for flagging this. This is because of an issue with the API that we're working through.

This raises an important couple of points that I'm hoping you'd be able to point me to some useful information/people in ROpenSci that might be able to help:
1. this package has been taken off CRAN now. I have (unintentionally) been breaking the CRAN policy for a while now. Each time the package has been taken off CRAN and I've done what I think then aligns with the policy before submitting it back to CRAN. The package has now been taken down without notifying me, so I'm concerned it might be difficult to get the package back on now because I might be black listed. Do you know the process to do that (or know someone who has experience of this)?
2. the last time the package was removed from CRAN, I changed all the tests that needed the live API to `skip_on_cran()`. This current failure has occurred because the vignettes use the API and because the API has had a few issues in the last few days the vignettes can't build. Is there a way to deal with this?

Any help or pointers for either of the questions would be really appreciated.
Thank you

**Comment by jeroen** [comment]
I don't think there is any special procedure, just resubmit as usual.

You should probably use a precomputed the vignette: https://ropensci.org/technotes/2019/12/08/precompute-vignettes/

**Comment by sebastian-fox** [comment]
Thanks, that's really helpful. I will precompute the vignette - that's a good idea.

Since writing I received an email from CRAN asking me not to resubmit the package. I will ask other ROpenSci volunteers to see whether they have any thoughts.

**Comment by sebastian-fox** [comment]
I've just been speaking with Maëlle about installing package from `repos = "https://dev.ropensci.org"` - this sounds like a good option for my situation. Do you know if you get information about download counts for the packages?

**Comment by sebastian-fox** [comment]
I think the issue with the API that caused this have been resolved. Is there any way to trigger a a rebuild?

**Comment by jeroen** [comment]
Sure I'll trigger a rebuild. You can also trigger a build yourself by pushing a commit.

**Comment by jeroen** [comment]
Thanks it seems fixed. Your docs are now updated: https://docs.ropensci.org/fingertipsR
